<?php
  /**
   * This file is part of the Achievo ATK distribution.
   * Detailed copyright and licensing information can be found
   * in the doc/COPYRIGHT and doc/LICENSE files which should be 
   * included in the distribution.
   *
   * @package atk   
   *
   * @copyright (c)2000-2004 Ibuildings.nl BV
   * @license http://www.achievo.org/atk/licensing ATK Open Source License
   *
   * @version $Revision: 5.25 $
   * $Id: version.inc,v 5.25 2006/03/14 20:40:56 ivo Exp $
   */
   
  /** 
   * The current atk version
   */
  $atk_version = "5.5.1";
  $atk_state   = "development";
?>
