<?php
/**
 * This file is part of the Achievo ATK distribution.
 * Detailed copyright and licensing information can be found
 * in the doc/COPYRIGHT and doc/LICENSE files which should be
 * included in the distribution.
 *
 * @package atk
 * @subpackage meta
 *
 * @copyright (c) 2004-2005 Peter C. Verhage
 * @license http://www.achievo.org/atk/licensing ATK Open Source License
 *
 * @version $Revision: 1.2 $
 * $Id: class.atkmetatools.inc,v 1.2 2006/01/09 08:58:58 peter Exp $
 */
 
/**
 * The ATK meta class consists of several *static* methods which are used
 * by the ATK meta node and related classes, but might also be used for
 * other purposes.
 * 
 * @author Peter C. Verhage <peter@achievo.org>
 *
 * @package atk
 * @subpackage meta
 */
class atkMetaTools
{
}
?>