<?php
  /**
   * This file is part of the Achievo ATK distribution.
   * Detailed copyright and licensing information can be found
   * in the doc/COPYRIGHT and doc/LICENSE files which should be
   * included in the distribution.
   *
   * @package atk
   * @subpackage themes
   *
   * @copyright (c)2000-2004 Ibuildings.nl BV
   * @license http://www.achievo.org/atk/licensing ATK Open Source License
   *
   * @version $Revision: 1.4 $
   * $Id: themedef.inc,v 1.4 2007/08/26 20:32:21 sandy Exp $
   */

  /**
   * Theme definition
   */
  $theme['basetheme'] = 'achievo_modern';
  $theme['basethemelocation'] = 'atk';


?>