<?php

  /**
   * This file is part of the Achievo ATK distribution.
   * Detailed copyright and licensing information can be found
   * in the doc/COPYRIGHT and doc/LICENSE files which should be
   * included in the distribution.
   *
   * @package atk
   * @subpackage themes
   *
   * @copyright (c)2000-2004 Ibuildings.nl BV
   * @license http://www.achievo.org/atk/licensing ATK Open Source License
   *
   * @version $Revision: 5.5 $
   * $Id: themedef.inc,v 5.5 2006/05/17 23:19:31 ivo Exp $
   */

  /** Theme definition */
  $theme["highlight"] = "#c5d7ff";
  $theme["select"]    = "#96a7ff";

  $theme["tabtype"] = "dhtml";
?>