<?php
  /**
   * This file is part of the Achievo ATK distribution.
   * Detailed copyright and licensing information can be found
   * in the doc/COPYRIGHT and doc/LICENSE files which should be
   * included in the distribution.
   *
   * @package atk
   * @subpackage themes
   *
   * @copyright (c)2000-2004 Ibuildings.nl BV
   * @license http://www.achievo.org/atk/licensing ATK Open Source License
   *
   * @version $Revision: 1.2 $
   * $Id: themedef.inc,v 1.2 2007/05/04 13:46:18 ivo Exp $
   */

  /**
   * Theme definition
   */
  $theme["tabtype"] = "dhtml";
  $theme["recordlist_orientation"]='right';
  $theme['compatible_menus'] = array('modern');
  $theme['modern_menu_compat'] = true;
  $theme['frame_top_height']=149;
  $theme['frame_menu_width']=210;
?>
